---
- name: Create operator resource files
  k8s:
    state: present
    namespace: "{{ _namespace }}"
    definition: "{{ lookup('file', role_path ~ '/files/datagrid/operator/{{ item }}.yml' ) | from_yaml }}"
  with_items:
  - crd
  - role
  - sa

- name: Create operator resource templates
  k8s:
    state: present
    namespace: "{{ _namespace }}"
    definition: "{{ lookup('template', role_path ~ '/templates/datagrid/operator/{{ item }}.j2' ) | from_yaml }}"
  with_items:
  - rolebinding
  - deployment

- name: Wait until infinispan-operator is running
  command: >
    oc rollout status Deployment/infinispan-operator --watch=true -n "{{ _namespace }}"

- name: Create Infinispan
  k8s:
    state: present
    namespace: "{{ _namespace }}"
    definition: "{{ lookup('template', role_path ~ '/files/datagrid/cluster.yml' ) | from_yaml }}"

- name: Wait until Infinispan is Deployed
  command: >
    oc get infinispan/example-infinispan -o jsonpath='{.status.conditions[?(@.type=="wellFormed")].status}' -n "{{ _namespace }}"
  register: infinispan
  retries: "{{ _retry }}"
  delay: "{{ _delay }}"
  until: infinispan.stdout == "True"

- name: Get Infinispan hotrod service address
  command: >
    oc get svc/example-infinispan -o jsonpath='{.metadata.name}{":"}{.spec.ports[?(@.name=="hotrod")].port}' -n "{{ _namespace }}"
  register: hotrod_clients