---
- name: Create operator resource files
  k8s:
    state: present
    namespace: "{{ _namespace }}"
    definition: "{{ lookup('file', role_path ~ '/files/businessautomation/operator/{{ item }}.yml' ) | from_yaml }}"
  with_items:
  - crd
  - role
  - sa

- name: Create operator resource templates
  k8s:
    state: present
    namespace: "{{ _namespace }}"
    definition: "{{ lookup('template', role_path ~ '/templates/businessautomation/operator/{{ item }}.j2' ) | from_yaml }}"
  with_items:
  - rolebinding
  - deployment

- name: Wait until business-automation-operator is running
  command: >
    oc rollout status Deployment/business-automation-operator --watch=true -n "{{ _namespace }}"

- name: Create Kie App
  k8s:
    state: present
    namespace: "{{ _namespace }}"
    definition: "{{ lookup('file', role_path ~ '/files/businessautomation/kie.yml' ) | from_yaml }}"

- name: Wait until KieApp has Deployed condition
  command: >
    oc get kieapp/rhpam-authoring -o jsonpath='{.status.conditions[?(@.type=="Deployed")].status}' -n "{{ _namespace }}"
  register: kieapp
  retries: "{{ _retry }}"
  delay: "{{ _delay }}"
  until: kieapp.stdout == "True"

- name: Check KieServer is running
  command: >
    oc rollout status DeploymentConfig/rhpam-authoring-kieserver --watch=true -n "{{ _namespace }}"

- name: Check BusinessCentral is running
  command: >
    oc rollout status DeploymentConfig/rhpam-authoring-rhpamcentr --watch=true -n "{{ _namespace }}"
